
<?php
$dbman = new dbmanager();
//[contact-form-7 id="497" title="Challenge and address stigma, prejudice and discrimination"]
$challenge_and_address_stigma_prejudice_and_discrimination = array(

	'tom_r1c1' => 'input_textarea',
	'ci_r1c2'  => 'input_textarea',
	'apwd_r1c3'=> 'input_textarea',
	'racd_r1c4'=> 'input_textarea',
	'atnb_r1c5'=> 'input_textarea',
	'tom_r2c1' => 'input_textarea',
	'ci_r2c2'  => 'input_textarea',
	'apwd_r2c3'=> 'input_textarea',
	'racd_r2c4'=> 'input_textarea',
	'atnb_r2c5'=> 'input_textarea',
    'tom_r3c1' => 'input_textarea',
    'ci_r3c2'  => 'input_textarea',
    'apwd_r3c3'=> 'input_textarea',
    'racd_r3c4'=> 'input_textarea',
    'atnb_r3c5'=> 'input_textarea',
    'tom_r4c1' => 'input_textarea',
    'ci_r4c2'  => 'input_textarea',
    'apwd_r4c3'=> 'input_textarea',
    'racd_r4c4'=> 'input_textarea',
    'atnb_r4c5'=> 'input_textarea',
    'tom_r5c1' => 'input_textarea',
    'ci_r5c2'  => 'input_textarea',
    'apwd_r5c3'=> 'input_textarea',
    'racd_r5c4'=> 'input_textarea',
    'atnb_r5c5'=> 'input_textarea',
     'n_r1c1'  => 'input_text',
     'ci_r1c2' => 'input_text',
	  'n_r2c1' => 'input_text',
	  'ci_r2c2'=> 'input_text',
	  'n_r3c1' => 'input_text',
	  'ci_r3c2'=> 'input_text',
	  'n_r4c1' => 'input_text',
	  'ci_r4c2'=> 'input_text',
	  'n_r5c1' => 'input_text',
	  'ci_r5c2'=> 'input_text',
	  'cop_r1' => 'input_text',
	  'cop_r2' => 'input_text',
	  'cop_r3' => 'input_text',
	  'cop_r4' => 'input_text',
	  'cop_r5' => 'input_text',
       'n_r1c1'=> 'input_text',
      'ci_r1c2'=> 'input_text',
       'n_r2c1'=> 'input_text',
      'ci_r2c2'=> 'input_text',
       'n_r3c1'=> 'input_text',
      'ci_r3c2'=> 'input_text',
       'n_r4c2'=> 'input_text',
      'ci_r4c2'=> 'input_text',
       'n_r5c2'=> 'input_text',
      'ci_r5c2'=> 'input_text',
     'n1_r1c1' => 'input_text',
     'ci1_r1c2'=> 'input_text',
     'n1_r2c1' => 'input_text',
     'ci1_r2c2'=> 'input_text',
     'n1_r3c1' => 'input_text',
    'ci1_r3c2' => 'input_text',
     'n1_r4c1' => 'input_text',
    'ci1_r4c2' => 'input_text',
     'n1_r5c1' => 'input_text',
    'ci1_r5c2' => 'input_text',
     'ln_r1c1' => 'input_textarea',
    'olc_r1c2' => 'input_textarea',
    'soi_r1c3' => 'input_textarea',
     'ci_r1c4' => 'input_textarea',
     'ln_r2c1' => 'input_textarea',
    'olc_r2c2' => 'input_textarea',
    'soi_r2c3' => 'input_textarea',
     'ci_r2c4' => 'input_textarea',
     'ln_r3c1' => 'input_textarea',
    'olc_r3c2' => 'input_textarea',
    'soi_r3c3' => 'input_textarea',
     'ci_r3c4' => 'input_textarea',
     'ln_r4c1' => 'input_textarea',
    'olc_r4c2' => 'input_textarea',
    'soi_r4c3' => 'input_textarea',
     'ci_r4c4' => 'input_textarea',
      'a_r1c1' => 'input_text',
     'pp_r1c2' => 'input_text',
      'a_r2c1' => 'input_text',
     'pp_r2c2' => 'input_text',
      'a_r3c1' => 'input_text',
     'pp_r3c2' => 'input_text',
      'a_r4c1' => 'input_text',
     'pp_r4c2' => 'input_text',
      'a_r5c1' => 'input_text',
     'pp_r5c2' => 'input_text' );
	
$dbman->table_create('challenge_and_address_stigma_prejudice_and_discrimination', $challenge_and_address_stigma_prejudice_and_discrimination);


$dbman = new dbmanager();
//[contact-form-7 id="511" title="Provide support for parents"]
$provide_support_for_parents = array(

  's1_r1c1' => 'input_textarea',
  'l1_r1c2'  => 'input_textarea',
  'ci_r1c3'=> 'input_textarea',
  's1_r2c1'=> 'input_textarea',
  'l1_r2c2'=> 'input_textarea',
  'ci_r2c3' => 'input_textarea',
  's1_r3c1'  => 'input_textarea',
  'l1_r3c2'=> 'input_textarea',
  'ci_r3c3'=> 'input_textarea',
  's1_r4c1'=> 'input_textarea',
    'l1_r4c2' => 'input_textarea',
    'ci_r4c3'  => 'input_textarea',
    's1_r5c1'=> 'input_textarea',
    'l1_r5c2'=> 'input_textarea',
    'ci_r5c3'=> 'input_textarea',
    'afti_check1' => 'input_checkbox',
    'iodp_r1c2' => 'input_textarea',
    'wwsp_check1'=> 'input_checkbox',
    'sp_r1c1' => 'input_textarea',
    'ci_r1c2'  => 'input_textarea',
    'aoe_r1c3'=> 'input_textarea',
    'sp_r2c1'=> 'input_textarea',
    'ci_r2c2'=> 'input_textarea',
    'aoe_r2c3' => 'input_textarea',
    'sp_r3c1'  => 'input_textarea',
    'aci_r3c2'=> 'input_textarea',
    'aoe_r3c3'=> 'input_textarea',
    'sp_r4c1'=> 'input_textarea',
    'ci_r4c2'=> 'input_textarea',
    'aoe_r4c3'=> 'input_textarea',
    'dasr_check1'=> 'input_checkbox',
    'sopn_r1c1' => 'input_textarea',
    'cii_r1c2 '  => 'input_textarea',             
    'tosp_r1c3'=> 'input_textarea',
    'sopn_r2c1'=> 'input_textarea',
    'cii_r2c2'=> 'input_textarea',
    'tosp_r2c3' => 'input_textarea',
    'sopn_r3c1'  => 'input_textarea',
    'cii_r3c2'=> 'input_textarea',
    'tosp_r3c3'=> 'input_textarea',
    'sopn_r4c1'=> 'input_textarea',
    'cii_r4c2'=> 'input_textarea',
    'tosp_r4c3'=> 'input_textarea' );
  
$dbman->table_create('provide_support_for_parents', $provide_support_for_parents);




?>